<?php
/**
 * Plugin Name:       wps-simple-hooks-modifier
 * Plugin URI:        
 * Description:       
 * Version:           1.0.0
 * Author:            Note
 * Author URI:        https://github.com/notefox
 * Text Domain:       wpsshm
 * Domain Path:       /english
 *
 * Generated by WordPress Plugin Generator v1.0.1 (wordpressplugingenerator.com)
 *
 */

// Prevent to access the file from outside of WordPress
if(!defined('ABSPATH')) {
	exit;
}
if(!function_exists('wp_get_current_user')) {
	include(ABSPATH . 'wp-includes/pluggable.php');
}

class wpsshm_Loader {
	public $config = [
		'name' => 'wps-simple-hooks-modifier',
		'version' => '1.0.0',
		'textDomain' => 'wpsshm',
		'textDomainPath' => 'english',
		'slug' => 'wps-simple-hooks-modifier',
		'prefix' => 'wpsshm',
		'prefixSeparator' => '_'
	];
	
	//
	public function __construct() {
		self::init();

		self::start();
	}

	/**
	 * Initialize the plugin
	 */
	private function init() {
	}

	
	/**
	 * Deactivates the plugin due to the missing requirements.
	 */
	public function deactivate() {
		if(current_user_can('activate_plugins') && is_plugin_active(plugin_basename(__FILE__))) {
			deactivate_plugins(plugin_basename(__FILE__));
	
			// Hide the default "Plugin activated" notice
			if(isset($_GET['activate'])) {
				unset($_GET['activate']);
			}
		}
	}

	/**
	 * Starting the plugin.
	 */
	public function start() {
		require_once plugin_dir_path(__FILE__) . 'classes/plugin.php';
		$plugin = new wpsshm_Plugin($this->config);

		register_activation_hook(__FILE__, [&$plugin, 'activate']);
		register_deactivation_hook(__FILE__, [&$plugin, 'deactivate']);
	}
}

$wpsshm = new wpsshm_Loader();
